// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLwOyp8lpkDnKS2iBdbccKWQMLHam4QA',
    appId: '1:306959471555:android:9f1e72df3d704ee988e376',
    messagingSenderId: '306959471555',
    projectId: 'portal-berita-bpkad',
    storageBucket: 'portal-berita-bpkad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcN2sBiXWtmMxRhhpguc_I9gjT0EHGt5U',
    appId: '1:306959471555:ios:1e866f6a3d4940ac88e376',
    messagingSenderId: '306959471555',
    projectId: 'portal-berita-bpkad',
    storageBucket: 'portal-berita-bpkad.appspot.com',
    androidClientId: '306959471555-ljf8ihusc7247okv3qr4iigui8msgqam.apps.googleusercontent.com',
    iosClientId: '306959471555-rbh5lhl1uhprb69tuinn1g00f2qedue1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpkadNewsApp',
  );
}
